[package]
name     = "app"
version  = "0.1.0"
edition  = "2021"
resolver = "2"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy         = { version = "0.13" }
wasm-bindgen = { version = "0.2"  }
